name: identity
description: Microservice Architecture Demo identity module UI
version: 0.0.1
homepage: https://github.com/MarkoMajamaki/Microservice-Architecture-Demo
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../../../core/frontend/shared
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.7
  get_it: ^7.2.0
  http: ^0.13.4
  modulary: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
  - lang/ 
  - images/
