# Trigger if pushed chanes to beta or prod branch
trigger:
  branches:
    include: 
    - beta
    - prod
  paths:
    include:
    - infra
    
variables:
- name: env
  value: variables['Build.SourceBranchName']

stages:
- stage: Validate
  jobs:
  - template: stages/infra_validate.yml
    parameters:
      env: $(env)
- stage: Plan
  jobs:
  - template: stages/infra_plan.yml
    parameters:
      env: $(env)
- stage: Apply
  jobs:
  - template: stages/infra_apply.yml
    parameters:
      env: $(env)
