parameters:
  env: ''

jobs:
- job: Build
  displayName: Build and push to ACR
  steps:

  - task: Docker@2
    displayName: BasketApi
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'basket-api'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/modules/basket/backend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    displayName: CatalogApi
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'catalog-api'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/modules/catalog/backend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    displayName: IdentityApi
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'identity-api'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/modules/identity/backend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest
  
  - task: Docker@2
    displayName: OrderApi
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'order-api'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/modules/order/backend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    displayName: Frontend
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'frontend'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/app/frontend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest