parameters:
  env: ''

jobs:
- job: Build
  displayName: Build and push to ACR
  steps:

  # Build CatalogApi and push to ACR
  - task: Docker@2
    displayName: CatalogApi - Build and push to ACR
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'catalog-api'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/modules/catalog/backend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest

  # Build BasketApi and push to ACR
  - task: Docker@2
    displayName: BasketApi - Build and push to ACR
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'basket-api'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/modules/basket/backend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest

  # Build OrderApi and push to ACR
  - task: Docker@2
    displayName: OrderApi - Build and push to ACR
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'order-api'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/modules/order/backend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest

  # Build IdentityApi and push to ACR
  - task: Docker@2
    displayName: IdentityApi - Build and push to ACR
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'identity-api'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/modules/Identity/backend/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest
  
  # Build Frontend and push to ACR
  - task: Docker@2
    displayName: Frontend - Build and push to ACR
    inputs:
      containerRegistery: 'microservicedemoacr${{ parameters.env }}'
      repository: 'frontend'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourceDictionary)/src/core/frontend/app/Dockerfile'
      buildContext: '.'
      tags: |
        $(Build.BuildId)
        latest