jobs:
  - job: Test
    displayName: Run server tests
    steps:

    # Order module

    - task: DotNetCoreCLI@2
      displayName: OrderApi.IntegrationTest
      inputs:
        command: 'test'
        projects: 'src/modules/order/backend/Tests/OrderApi.IntegrationTest/OrderApi.IntegrationTest.csproj'
        testRunTitle: 'OrderApi integration tests'      

    - task: DotNetCoreCLI@2
      displayName: OrderApi.UnitTest
      inputs:
        command: 'test'
        projects: 'src/modules/order/backend/Tests/OrderApi.UnitTest/OrderApi.UnitTest.csproj'
        testRunTitle: 'OrderApi unit tests'      

    # Identity module

    - task: DotNetCoreCLI@2
      displayName: Identity.IntegrationTest
      inputs:
        command: 'test'
        projects: 'src/modules/Identity/backend/Tests/IdentityApi.IntegrationTest/IdentityApi.IntegrationTest.csproj'
        testRunTitle: 'IdentityApi integraition tests'      

    - task: DotNetCoreCLI@2
      displayName: Identity.UnitTest
      inputs:
        command: 'test'
        projects: 'src/modules/Identity/backend/Tests/IdentityApi.UnitTest/IdentityApi.UnitTest.csproj'
        testRunTitle: 'IdentityApi unit tests'