apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-api-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $clientId
    keyvaultName: $keyvaultName
    objects: |
      array:
        - |
          objectName: ORDER--CONNECTIONSTRING
          objectType: secret
          objectVersion: ""
    tenantId: $tenantId
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: identity-api-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $clientId
    keyvaultName: $keyvaultName
    objects: |
      array:
        - |
          objectName: IDENTITY--CONNECTIONSTRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: FACEBOOK--APPID              
          objectType: secret
          objectVersion: ""
        - |
          objectName: FACEBOOK--APPSECRET              
          objectType: secret
          objectVersion: ""
        - |
          objectName: GOOGLE--CLIENTID              
          objectType: secret
          objectVersion: ""
        - |
          objectName: GOOGLE--CLIENTSECRET              
          objectType: secret
          objectVersion: ""
    tenantId: $tenantId
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jwt-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $clientId
    keyvaultName: $keyvaultName
    objects: |
      array:
        - |
          objectName: JWT--SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: JWT--VALIDAUDIENCE              
          objectType: secret
          objectVersion: ""
        - |
          objectName: JWT--VALIDISSUER
          objectType: secret
          objectVersion: ""
    tenantId: $tenantId
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rabbitmq-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $clientId
    keyvaultName: $keyvaultName
    objects: |
      array:
        - |
          objectName: RABBIT--HOSTNAME              
          objectType: secret
          objectVersion: ""
        - |
          objectName: RABBIT--PORT              
          objectType: secret
          objectVersion: ""
        - |
          objectName: RABBIT--USERNAME              
          objectType: secret
          objectVersion: ""
        - |
          objectName: RABBIT--PASSWORD              
          objectType: secret
          objectVersion: ""
    tenantId: $tenantId
---