apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: order-api-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $clientId
    keyvaultName: $keyvaultName
    objects: |
      array:
        - |
          objectName: sqlserver--server
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqlserver--port              
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqlserver--username
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqlserver--password              
          objectType: secret
          objectVersion: ""
        - |
          objectName: order--databasename  
          objectType: secret
          objectVersion: ""
        - |
          objectName: rabbitmq--hostname              
          objectType: secret
          objectVersion: ""
        - |
          objectName: rabbitmq--port              
          objectType: secret
          objectVersion: ""
        - |
          objectName: rabbitmq--username              
          objectType: secret
          objectVersion: ""
        - |
          objectName: rabbitmq--password              
          objectType: secret
          objectVersion: ""
    tenantId: $tenantId
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: identity-api-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $clientId
    keyvaultName: $keyvaultName
    objects: |
      array:
        - |
          objectName: sqlserver--server
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqlserver--port              
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqlserver--username
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqlserver--password              
          objectType: secret
          objectVersion: ""
        - |
          objectName: identity--databasename         
          objectType: secret
          objectVersion: ""
        - |
          objectName: facebook--appid              
          objectType: secret
          objectVersion: ""
        - |
          objectName: facebook--appsecret              
          objectType: secret
          objectVersion: ""
        - |
          objectName: google--clientid              
          objectType: secret
          objectVersion: ""
        - |
          objectName: google--clientsecret              
          objectType: secret
          objectVersion: ""
    tenantId: $tenantId
