name: shared
description: Microservice Architecture Demo shared package to every module frontend
version: 0.0.1
homepage: https://github.com/MarkoMajamaki/Microservice-Architecture-Demo
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: