apiVersion: v1
kind: Secret
metadata:
  name: identity-api-secrets
type: Opaque
data:
  IDENTITY--CONNECTIONSTRING: "aWRlbnRpdHktZGI=" # identity-db
  FACEBOOK--APPID: "WW91cl9GYWNlYm9va19BcHBJZA==" # Your_Facebook_AppId
  FACEBOOK--APPSECRET: "WW91cl9GYWNlYm9va19BcHBTZWNyZXQ=" # Your_Facebook_AppSecret
  GOOGLE--CLIENTID:  "WW91cl9Hb29nbGVfQ2xpZW50SWQ=" # Your_Google_ClientId
  GOOGLE--CLIENTSECRET: "WW91cl9Hb29nbGVfQ2xpZW50X1NlY3JldA==" # Your_Google_Client_Secret
