apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  JWT__SECRET: "QnlZTTAwME9MbE1RRzZWVlZwMU9IN1h6eXI3Z0h1dzFxdlVDNWRjR3QzU05N" # ByYM000OLlMQG6VVVp1OH7Xzyr7gHuw1qvUC5dcGt3SNM
  JWT__VALIDAUDIENCE: "WW91cl9KV1RfVmFsaWRhdWRpZW5jZQo=" # Your_JWT_Validaudience
  JWT__VALIDISSUER: "WW91cl9KV1RfVmFsaWRJc3N1ZXIK" # Your_JWT_ValidIssuer