apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  RABBITMQ--HOSTNAME: "cmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==" # rabbitmq.default.svc.cluster.local
  RABBITMQ--PORT: "NTY3Mg==" # 5672
  RABBITMQ--USERNAME: "Z3Vlc3Q=" # guest
  RABBITMQ--PASSWORD: "Z3Vlc3Q=" # guest