version: "3.9"

services:

  gateway:
    image: microservicedemoacrbeta.azurecr.io/gateway:latest
    container_name: gateway
    build:
      context: ../../
      dockerfile: src/gateway/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
    ports:
      - "8001:8001"
      - "8000:8000"

  frontend:
    image: microservicedemoacrbeta.azurecr.io/frontend:latest
    container_name: frontend
    build:
      context: ../../
      dockerfile: src/app/frontend/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
    ports:
      - "80"

  # TODO: Ports should be unique for each container
  #
  # identityapi:
  #   image: microservicedemoacrbeta.azurecr.io/identity-api:latest
  #   container_name: identityapi
  #   restart: on-failure
  #   build:
  #     context: ../../
  #     dockerfile: src/modules/identity/backend/Dockerfile
  #   depends_on: 
  #     - sqlserver
  #     - rabbitmq
  #   env_file: 
  #     - ../.env/identity-api.env
  #     - ../.env/rabbitmq.env
  #     - ../.env/jwt.env
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 200M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 100M
  #   ports:
  #     - "80"
  #
  # orderapi:
  #   image: microservicedemoacrbeta.azurecr.io/order-api:latest
  #   container_name: orderapi
  #   restart: on-failure   
  #   build:
  #     context: ../../
  #     dockerfile: src/modules/order/backend/Dockerfile
  #   depends_on: 
  #     - sqlserver
  #     - rabbitmq
  #   env_file: 
  #     - ../.env/order-api.env
  #     - ../.env/rabbitmq.env
  #     - ../.env/jwt.env
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 200M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 100M
  #   ports:
  #     - "80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "loc4LdevP4ss#"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
    ports:
      - "1433"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
    ports:
      - "5672"
      - "15672"
