version: "3.9"

services:

  gateway:
    image: envoyproxy/envoy:v1.20.2
    container_name: gateway
    ports:
      - "8001:8001"
      - "8000:80"
    volumes:
      - ../../src/gateway/envoy.yml:/etc/envoy/envoy.yaml

  frontend:
    image: microservice_demo/frontend:latest
    container_name: frontend
    build:
      context: ../../
      dockerfile: src/app/frontend/Dockerfile
    ports:
      - "5001:80"

  identityapi:
    image: microservice_demo/identity-api:latest
    container_name: identityapi
    restart: on-failure
    build:
      context: ../../
      dockerfile: src/modules/identity/backend/Dockerfile
    depends_on: 
      - sqlserver
      - rabbitmq
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    env_file: 
      - ../.env/identity-api.env
      - ../.env/rabbitmq.env
      - ../.env/jwt.env
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    ports:
      - "5002:80"

  orderapi:
    image: microservice_demo/order-api:latest
    container_name: orderapi
    restart: on-failure   
    build:
      context: ../../
      dockerfile: src/modules/order/backend/Dockerfile
    depends_on: 
      - sqlserver
      - rabbitmq
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    env_file: 
      - ../.env/order-api.env
      - ../.env/rabbitmq.env
      - ../.env/jwt.env
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    ports:
      - "5003:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "loc4LdevP4ss#"
    ports:
      - "1433:1433"
    volumes:
      - ../../.volumes/sqlserver-data:/var/opt/mssql/data
      - ../../.volumes/sqlserver-logs:/var/opt/mssql/log
      - ../../.volumes/sqlserver-secrets:/var/opt/mssql/secrets
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
